### ISSUE TITLE
Node gyp problem (

### ISSUE THREAD

**Issue by mindfulme** [alexnm/react-ssr#28]
These steps do not help: https://codeforgeek.com/make-failed-with-exit-code-2/#:~:text=The%20%E2%80%9CMake%20Failed%20with%20Exit,during%20the%20node%20modules%20installation.&text=Make%20sure%20you%20have%20latest,is%20installed%20in%20your%20system.

```
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
5 errors generated.
make: *** [Release/obj.target/iltorb/src/dec/stream_decode.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/rostyslav/.nvm/versions/node/v12.16.1/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rostyslav/Desktop/ssr/node_modules/iltorb
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for bundlesize@0.16.0: wanted: {"npm":"^5.0.0"} (current: {"node":"12.16.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: bundlesize@0.16.0
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.1","npm":"6.13.4"})
```

**Comment by mindfulme** [comment]
Solution: use nodejs v8, and to use the higher version update package.json modules
