### ISSUE TITLE
Can't run dist app.bundle.js 

### ISSUE THREAD

**Issue by lucasscariot** [alexnm/react-ssr#8]
Hi! Thanks for this repository!

I'm having trouble generating a production build.

After cloning, and installing dependancies, I executed an `npm run build`.
A dist folder is created with `app.bundle.js`, `app.bundle.js.map` and `webpack-report.html` inside.

Then I tried to run the `app.bundle.js` file and there is a following error: 

```
ReferenceError: self is not defined
    at Module.<anonymous> (/Users/lucas/goinfre/react-ssr/dist/app.bundle.js:30:3751)
    at n (/Users/lucas/goinfre/react-ssr/dist/app.bundle.js:1:172)
    at Object.<anonymous> (/Users/lucas/goinfre/react-ssr/dist/app.bundle.js:6:3603)
    at n (/Users/lucas/goinfre/react-ssr/dist/app.bundle.js:1:172)
    at Module.<anonymous> (/Users/lucas/goinfre/react-ssr/dist/app.bundle.js:41:45083)
    at n (/Users/lucas/goinfre/react-ssr/dist/app.bundle.js:1:172)
    at /Users/lucas/goinfre/react-ssr/dist/app.bundle.js:1:964
    at Object.<anonymous> (/Users/lucas/goinfre/react-ssr/dist/app.bundle.js:1:974)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by lucasscariot** [comment]
Found out I still have to run `node index.js` with the production `dist` folder. 👍

**Comment by kimprosh** [comment]
I run `node dist/app.bundle.js`  but still the above error

**Comment by mindfulme** [comment]
https://codeforgeek.com/make-failed-with-exit-code-2/#:~:text=The%20%E2%80%9CMake%20Failed%20with%20Exit,during%20the%20node%20modules%20installation.&text=Make%20sure%20you%20have%20latest,is%20installed%20in%20your%20system.
